# -*- coding: utf-8 -*-
"""generate_lstm_diagram.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FtJF8y4xGiBDp2tTEaR5FDyfyx2d1J_C
"""

import sys

# Install graphviz system-wide
!apt-get install -y graphviz

# Install the Python graphviz library
!{sys.executable} -m pip install graphviz

from graphviz import Digraph

# Create a directed graph
dot = Digraph(comment='LSTM Workflow')
dot.attr(rankdir='TB')  # Top to Bottom direction

# Define nodes with box shapes
dot.node('A', 'Raw CSV Data', shape='box')
dot.node('B', 'Data Cleaning & Merge', shape='box')
dot.node('C', 'Feature Engineering\n(Scaling + Encoding + Sequences)', shape='box')
dot.node('D', 'LSTM Model\n(Training + Tuning)', shape='box')
dot.node('E', 'Predictions (Scaled)', shape='box')
dot.node('F', 'Inverse Scaling → Real °C', shape='box')
dot.node('G', 'RMSE & R² +\nPerformance Visualization', shape='box')

# Define edges
dot.edges(['AB', 'BC', 'CD', 'DE', 'EF', 'FG'])

# Render the graph to a file (e.g., 'lstm_workflow.png')
# Note: You need Graphviz installed on your system for this to work.
dot.render('lstm_workflow', format='png') # Removed view=True

print("Graphviz code generated. Run this in an environment with Graphviz installed to view the diagram.")
print(dot.source)

from IPython.display import Image
Image('lstm_workflow.png')